############################################################
#     DO NOT TOUCH 
############################################################
# Automatically created using make_makefile.R

############################################################
# Targets for  4 reps per variety
############################################################
make4: results-2/results-4-1.rds results-2/results-4-2.rds results-2/results-4-3.rds results-2/results-4-4.rds results-2/results-4-5.rds results-2/results-4-6.rds results-2/results-4-7.rds results-2/results-4-8.rds results-2/results-4-9.rds results-2/results-4-10.rds

results-2/results-4-1.rds: sim-script2.R sim-data/sim-4-1.rds
	R CMD BATCH --vanilla '--args r=4 i=1' sim-script2.R sim-4-1.Rout 

results-2/results-4-2.rds: sim-script2.R sim-data/sim-4-2.rds
	R CMD BATCH --vanilla '--args r=4 i=2' sim-script2.R sim-4-2.Rout 

results-2/results-4-3.rds: sim-script2.R sim-data/sim-4-3.rds
	R CMD BATCH --vanilla '--args r=4 i=3' sim-script2.R sim-4-3.Rout 

results-2/results-4-4.rds: sim-script2.R sim-data/sim-4-4.rds
	R CMD BATCH --vanilla '--args r=4 i=4' sim-script2.R sim-4-4.Rout 

results-2/results-4-5.rds: sim-script2.R sim-data/sim-4-5.rds
	R CMD BATCH --vanilla '--args r=4 i=5' sim-script2.R sim-4-5.Rout 

results-2/results-4-6.rds: sim-script2.R sim-data/sim-4-6.rds
	R CMD BATCH --vanilla '--args r=4 i=6' sim-script2.R sim-4-6.Rout 

results-2/results-4-7.rds: sim-script2.R sim-data/sim-4-7.rds
	R CMD BATCH --vanilla '--args r=4 i=7' sim-script2.R sim-4-7.Rout 

results-2/results-4-8.rds: sim-script2.R sim-data/sim-4-8.rds
	R CMD BATCH --vanilla '--args r=4 i=8' sim-script2.R sim-4-8.Rout 

results-2/results-4-9.rds: sim-script2.R sim-data/sim-4-9.rds
	R CMD BATCH --vanilla '--args r=4 i=9' sim-script2.R sim-4-9.Rout 

results-2/results-4-10.rds: sim-script2.R sim-data/sim-4-10.rds
	R CMD BATCH --vanilla '--args r=4 i=10' sim-script2.R sim-4-10.Rout 

clean4:
	rm -fv results-2/results-4-1.rds results-2/results-4-2.rds results-2/results-4-3.rds results-2/results-4-4.rds results-2/results-4-5.rds results-2/results-4-6.rds results-2/results-4-7.rds results-2/results-4-8.rds results-2/results-4-9.rds results-2/results-4-10.rds

############################################################
# Targets for  8 reps per variety
############################################################
make8: results-2/results-8-1.rds results-2/results-8-2.rds results-2/results-8-3.rds results-2/results-8-4.rds results-2/results-8-5.rds results-2/results-8-6.rds results-2/results-8-7.rds results-2/results-8-8.rds results-2/results-8-9.rds results-2/results-8-10.rds

results-2/results-8-1.rds: sim-script2.R sim-data/sim-8-1.rds
	R CMD BATCH --vanilla '--args r=8 i=1' sim-script2.R sim-8-1.Rout 

results-2/results-8-2.rds: sim-script2.R sim-data/sim-8-2.rds
	R CMD BATCH --vanilla '--args r=8 i=2' sim-script2.R sim-8-2.Rout 

results-2/results-8-3.rds: sim-script2.R sim-data/sim-8-3.rds
	R CMD BATCH --vanilla '--args r=8 i=3' sim-script2.R sim-8-3.Rout 

results-2/results-8-4.rds: sim-script2.R sim-data/sim-8-4.rds
	R CMD BATCH --vanilla '--args r=8 i=4' sim-script2.R sim-8-4.Rout 

results-2/results-8-5.rds: sim-script2.R sim-data/sim-8-5.rds
	R CMD BATCH --vanilla '--args r=8 i=5' sim-script2.R sim-8-5.Rout 

results-2/results-8-6.rds: sim-script2.R sim-data/sim-8-6.rds
	R CMD BATCH --vanilla '--args r=8 i=6' sim-script2.R sim-8-6.Rout 

results-2/results-8-7.rds: sim-script2.R sim-data/sim-8-7.rds
	R CMD BATCH --vanilla '--args r=8 i=7' sim-script2.R sim-8-7.Rout 

results-2/results-8-8.rds: sim-script2.R sim-data/sim-8-8.rds
	R CMD BATCH --vanilla '--args r=8 i=8' sim-script2.R sim-8-8.Rout 

results-2/results-8-9.rds: sim-script2.R sim-data/sim-8-9.rds
	R CMD BATCH --vanilla '--args r=8 i=9' sim-script2.R sim-8-9.Rout 

results-2/results-8-10.rds: sim-script2.R sim-data/sim-8-10.rds
	R CMD BATCH --vanilla '--args r=8 i=10' sim-script2.R sim-8-10.Rout 

clean8:
	rm -fv results-2/results-8-1.rds results-2/results-8-2.rds results-2/results-8-3.rds results-2/results-8-4.rds results-2/results-8-5.rds results-2/results-8-6.rds results-2/results-8-7.rds results-2/results-8-8.rds results-2/results-8-9.rds results-2/results-8-10.rds

############################################################
# Targets for  16 reps per variety
############################################################
make16: results-2/results-16-1.rds results-2/results-16-2.rds results-2/results-16-3.rds results-2/results-16-4.rds results-2/results-16-5.rds results-2/results-16-6.rds results-2/results-16-7.rds results-2/results-16-8.rds results-2/results-16-9.rds results-2/results-16-10.rds

results-2/results-16-1.rds: sim-script2.R sim-data/sim-16-1.rds
	R CMD BATCH --vanilla '--args r=16 i=1' sim-script2.R sim-16-1.Rout 

results-2/results-16-2.rds: sim-script2.R sim-data/sim-16-2.rds
	R CMD BATCH --vanilla '--args r=16 i=2' sim-script2.R sim-16-2.Rout 

results-2/results-16-3.rds: sim-script2.R sim-data/sim-16-3.rds
	R CMD BATCH --vanilla '--args r=16 i=3' sim-script2.R sim-16-3.Rout 

results-2/results-16-4.rds: sim-script2.R sim-data/sim-16-4.rds
	R CMD BATCH --vanilla '--args r=16 i=4' sim-script2.R sim-16-4.Rout 

results-2/results-16-5.rds: sim-script2.R sim-data/sim-16-5.rds
	R CMD BATCH --vanilla '--args r=16 i=5' sim-script2.R sim-16-5.Rout 

results-2/results-16-6.rds: sim-script2.R sim-data/sim-16-6.rds
	R CMD BATCH --vanilla '--args r=16 i=6' sim-script2.R sim-16-6.Rout 

results-2/results-16-7.rds: sim-script2.R sim-data/sim-16-7.rds
	R CMD BATCH --vanilla '--args r=16 i=7' sim-script2.R sim-16-7.Rout 

results-2/results-16-8.rds: sim-script2.R sim-data/sim-16-8.rds
	R CMD BATCH --vanilla '--args r=16 i=8' sim-script2.R sim-16-8.Rout 

results-2/results-16-9.rds: sim-script2.R sim-data/sim-16-9.rds
	R CMD BATCH --vanilla '--args r=16 i=9' sim-script2.R sim-16-9.Rout 

results-2/results-16-10.rds: sim-script2.R sim-data/sim-16-10.rds
	R CMD BATCH --vanilla '--args r=16 i=10' sim-script2.R sim-16-10.Rout 

clean16:
	rm -fv results-2/results-16-1.rds results-2/results-16-2.rds results-2/results-16-3.rds results-2/results-16-4.rds results-2/results-16-5.rds results-2/results-16-6.rds results-2/results-16-7.rds results-2/results-16-8.rds results-2/results-16-9.rds results-2/results-16-10.rds

