all: sim-results1.rds \
     sim-results2.rds \
     sim-results3.rds \
     sim-results4.rds \
     sim-results5.rds \
     sim-results6.rds \
     sim-results7.rds \
     sim-results8.rds \
     sim-results9.rds \
     sim-results10.rds \
     sim-results11.rds \
     sim-results12.rds \
     sim-results13.rds \
     sim-results14.rds \
     sim-results15.rds \
     sim-results16.rds \
     sim-results17.rds \
     sim-results18.rds \
     sim-results19.rds \
     sim-results20.rds \
     sim-results21.rds \
     sim-results22.rds \
     sim-results23.rds \
     sim-results24.rds \
     sim-results25.rds \
     sim-results26.rds \
     sim-results27.rds \
     sim-results28.rds \
     sim-results29.rds \
     sim-results30.rds 

sim-results1.rds: R CMD BATCH --vanilla '--args i=1' sim-script.R 
sim-results2.rds: R CMD BATCH --vanilla '--args i=2' sim-script.R 
sim-results3.rds: R CMD BATCH --vanilla '--args i=3' sim-script.R 
sim-results4.rds: R CMD BATCH --vanilla '--args i=4' sim-script.R 
sim-results5.rds: R CMD BATCH --vanilla '--args i=5' sim-script.R 
sim-results6.rds: R CMD BATCH --vanilla '--args i=6' sim-script.R 
sim-results7.rds: R CMD BATCH --vanilla '--args i=7' sim-script.R 
sim-results8.rds: R CMD BATCH --vanilla '--args i=8' sim-script.R 
sim-results9.rds: R CMD BATCH --vanilla '--args i=9' sim-script.R 
sim-results10.rds: R CMD BATCH --vanilla '--args i=10' sim-script.R 
sim-results11.rds: R CMD BATCH --vanilla '--args i=11' sim-script.R 
sim-results12.rds: R CMD BATCH --vanilla '--args i=12' sim-script.R 
sim-results13.rds: R CMD BATCH --vanilla '--args i=13' sim-script.R 
sim-results14.rds: R CMD BATCH --vanilla '--args i=14' sim-script.R 
sim-results15.rds: R CMD BATCH --vanilla '--args i=15' sim-script.R 
sim-results16.rds: R CMD BATCH --vanilla '--args i=16' sim-script.R 
sim-results17.rds: R CMD BATCH --vanilla '--args i=17' sim-script.R 
sim-results18.rds: R CMD BATCH --vanilla '--args i=18' sim-script.R 
sim-results19.rds: R CMD BATCH --vanilla '--args i=19' sim-script.R 
sim-results20.rds: R CMD BATCH --vanilla '--args i=20' sim-script.R 
sim-results21.rds: R CMD BATCH --vanilla '--args i=21' sim-script.R 
sim-results22.rds: R CMD BATCH --vanilla '--args i=22' sim-script.R 
sim-results23.rds: R CMD BATCH --vanilla '--args i=23' sim-script.R 
sim-results24.rds: R CMD BATCH --vanilla '--args i=24' sim-script.R 
sim-results25.rds: R CMD BATCH --vanilla '--args i=25' sim-script.R 
sim-results26.rds: R CMD BATCH --vanilla '--args i=26' sim-script.R 
sim-results27.rds: R CMD BATCH --vanilla '--args i=27' sim-script.R 
sim-results28.rds: R CMD BATCH --vanilla '--args i=28' sim-script.R 
sim-results29.rds: R CMD BATCH --vanilla '--args i=29' sim-script.R 
sim-results30.rds: R CMD BATCH --vanilla '--args i=30' sim-script.R 
